/*
 * Books service example
 *
 * Everything about books
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AppControllerFindOne - 
func AppControllerFindOne(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AppControllerListBookCategories - 
func AppControllerListBookCategories(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AppControllerListBooks - 
func AppControllerListBooks(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
