// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Sells struct {
	BookID     string  `json:"bookId"`
	SellsCount int     `json:"sellsCount"`
	MonthYear  *string `json:"monthYear"`
	StoreID    string  `json:"storeId"`
}

type Store struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Location string `json:"location"`
}
