package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/songtomtom/graphql-mesh-gateway/graphql/graph/model"
)

// Stores is the resolver for the stores field.
func (r *queryResolver) Stores(ctx context.Context) ([]*model.Store, error) {
	panic(fmt.Errorf("not implemented: Stores - stores"))
}

// BookSells is the resolver for the bookSells field.
func (r *queryResolver) BookSells(ctx context.Context, storeID string) ([]*model.Sells, error) {
	panic(fmt.Errorf("not implemented: BookSells - bookSells"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
