/*
 * Books service example
 *
 * Everything about books
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	openapi "github.com/songtomtom/graphql-mesh-gateway/rest-api/go"
	"log"
)

func main() {
	log.Printf("Server started")
	router := openapi.NewRouter()
	log.Fatal(router.Run(":3002"))
}
