sources:
  - name: Books
    handler:
      openapi:
        endpoint: http://localhost:3002/
  - name: Authors
    handler:
      grpc:
        endpoint: http://localhost:3003/
  - name: Stores
    handler:
      graphql:
        endpoint: http://localhost:3004/
serve:
  hostname: 0.0.0.0
  port: 80
  endpoint: /gateway/graphql
  browser: false
  playground: true