sources:
  - name: Books
    handler:
      openapi:
        endpoint: http://localhost:3002/
        source: ../rest-api/openapi3-definition.json
  - name: Authors
    handler:
      grpc:
        endpoint: http://localhost:3003/
        source: ../grpc/proto/v1/authors_service.proto
  - name: Stores
    handler:
      graphql:
        endpoint: http://localhost:3004/query
serve:
  hostname: 0.0.0.0
  port: 80
  endpoint: /
  browser: false
  playground: true