/*
 * Books service example
 *
 * Everything about books
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Category struct {

	Id string `json:"id"`

	Name string `json:"name"`
}
